#dataset
train_datafile: data/train_data.json
test_datafile: data/test_data.json
save_dir: save
force_rewrite: False

#split
val_split: 0.1
test_split: 0.9

#train
batch_size: 8
epochs: 1000
train_both: False
train_intent: True

#model
model_name: roberta-base
lr: 1e-6
wd: 1e-8
lr_drop_step: 50

#results
save_result_dir: save